targets:
  $default:
    builders:
      json_serializable:
        options:
          # https://pub.dartlang.org/packages/json_serializable
          use_wrappers: false
          any_map: false
          checked: false
          explicit_to_json: false
          generate_to_json_function: true
