name: tinhte_api
version: 1.0.0

author: Dao Hoang Son <daohoangson@gmail.com>

description: tinhte-api
homepage: https:/tinhte.vn

dependencies:
  http: ^0.12.0
  json_annotation: ^1.0.0

dev_dependencies:
  build_runner: ^0.10.0
  json_serializable: ^1.4.0
  test: ^1.3.3
